routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::name('admin.')
    ->prefix('admin')
    ->namespace('App\Http\Controllers\Admin')
    ->middleware(['auth', 'role:admin'])
    ->group(function () {
        Route::resource('user', 'UserController');
        Route::resource('permission', 'PermissionController');
        Route::resource('role', 'RoleController');
    });

Route::resource('barang', 'App\Http\Controllers\BarangController');
Route::get('my_cv', [App\Http\Controllers\CvController::class, 'index'])->name('my_cv');

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use App\Models\ms_barang;
use App\Models\log_db;
use App\Traits\FlashAlert;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;

class BarangController extends Controller
{
    use FlashAlert;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $barangs = ms_barang::paginate(10);
        return view('pages.barang.index', compact('barangs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.barang.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (request()->user()->isAbleTo('barang-create')){
            $this->validate($request, [
                'nm_barang' => ['required', 'string', 'max:255'],
                'merek_barang' => ['required', 'string', 'max:255'],
                'status' => ['required'],
            ]);
    
            $tmpData =[
                'nama' => $request->input('nm_barang'),
                'merek' => $request->input('merek_barang'),
                'status' => $request->input('status'),
            ];
    
            if(!empty($request->input('keterangan_barang')) && isset($request->keterangan_barang)){
                $tmpData['keterangan'] = $request->input('keterangan_barang');
            }else{
                $tmpData['keterangan'] = '-';
            }
    
            request()->user()->ms_barang()->create($tmpData);

            log_db::create([
                "id_user_act" => request()->user()->id,
                "note" => "INSERT DATA",
                "data" => json_encode($tmpData),
            ]);

    
            return redirect()->route('barang.index')->with($this->alertCreated());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $barang = ms_barang::findOrFail($id);
            if(!request()->user()){
                return view('pages.barang.edit', compact('barang'));
            }
            
            if (
                request()->user()->isAbleTo(['barang-update','barang-read'], $barang)
                ) {
                return view('pages.barang.edit', compact('barang'));
            } else {
                return redirect()->route('barang.index')->with($this->permissionDenied());
            }
        } catch (ModelNotFoundException $e) {
            return redirect()->route('barang.index')->with($this->alertNotFound());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $barang = ms_barang::findOrFail($id);

            if (
                request()->user()->hasRole(['superadmin', 'admin']) ||
                request()->user()->isAbleTo('barang-update', $barang)
            ) {
                $this->validate($request, [
                    'nm_barang' => ['required', 'string', 'max:255'],
                    'merek_barang' => ['required', 'string', 'max:255'],
                    'status' => ['required'],
                ]);

                $tmpData =[
                    'nama' => $request->input('nm_barang'),
                    'merek' => $request->input('merek_barang'),
                    'status' => $request->input('status'),
                ];

                if(!empty($request->input('keterangan_barang')) && isset($request->keterangan_barang)){
                    $tmpData['keterangan'] = $request->input('keterangan_barang');
                }else{
                    $tmpData['keterangan'] = '-';
                }

                log_db::create([
                    "id_user_act" => request()->user()->id,
                    "note" => "UPDATE DATA",
                    "data" => json_encode($barang),
                ]);
                $barang->update($tmpData);

                return redirect()->route('barang.index')->with($this->alertUpdated());
            } else {
                return redirect()->route('barang.index')->with($this->permissionDenied());
            }
        } catch (ModelNotFoundException $e) {
            return redirect()->route('barang.index')->with($this->alertNotFound());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {

            $barang = ms_barang::findOrFail($id);

            if (
                request()->user()->isAbleTo('barang-delete', $barang)
            ) {
                log_db::create([
                    "id_user_act" => request()->user()->id,
                    "note" => "DELETE DATA",
                    "data" => json_encode($barang),
                ]);
                $barang->delete();

                return redirect()->route('barang.index')->with($this->alertDeleted());
            } else {
                return redirect()->route('barang.index')->with($this->permissionDenied());
            }
        } catch (ModelNotFoundException $e) {
            return redirect()->route('barang.index')->with($this->alertNotFound());
        }
    }
}

resources/views/pages/barang/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Barang') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('barang.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="nm_barang" class="col-md-3 col-form-label text-md-right">{{ __('Nama Barang') }}</label>

                            <div class="col-md-7">
                                <input id="nm_barang" type="text" class="form-control @error('nama') is-invalid @enderror" name="nm_barang" value="{{ old('nm_barang') }}" required autocomplete="nm_barang" placeholder="Nama Barang" autofocus>

                                @error('nama')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="merek_barang" class="col-md-3 col-form-label text-md-right">{{ __('Merek') }}</label>

                            <div class="col-md-7">
                                <input id="merek_barang" type="text" class="form-control @error('merek') is-invalid @enderror" name="merek_barang" value="{{ old('merek_barang') }}" required autocomplete="merek_barang" placeholder="Merek Barang">

                                @error('merek')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="keterangan_barang" class="col-md-3 col-form-label text-md-right">{{ __('Keterangan') }}</label>

                            <div class="col-md-7">
                                <textarea name="keterangan_barang" id="keterangan_barang" cols="30" rows="3" autocomplete="body" class="form-control @error('keterangan') is-invalid @enderror">{{ old('keterangan_barang') }}</textarea>

                                @error('keterangan')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="status" class="col-md-3 col-form-label text-md-right">{{ __('Status') }}</label>

                            <div class="col-md-7">
                                <select name="status" id="status" class="form-control @error('status') is-invalid @enderror">
                                    <option value="0" {{ old('status') == 0 ? 'selected' : ''}}>Tidak Aktif</option>
                                    <option value="1" {{ old('status') == 1 ? 'selected' : ''}}>Aktif</option>
                                </select>

                                @error('status')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-7 offset-md-3">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                                <a href="{{ route('barang.index') }}" class="btn btn-danger text-white">{{ __('Cancel') }}</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/barang/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Barang') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('barang.update', $barang->id) }}">
                        @csrf @method('PUT')

                        <div class="form-group row">
                            <label for="nm_barang" class="col-md-3 col-form-label text-md-right">{{ __('Nama Barang') }}</label>

                            <div class="col-md-7">
                                <input id="nm_barang" type="text" class="form-control @error('nama') is-invalid @enderror" name="nm_barang" value="{{ $barang->nama }}" required autocomplete="nm_barang" placeholder="Nama Barang" autofocus>

                                @error('nama')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="merek_barang" class="col-md-3 col-form-label text-md-right">{{ __('Merek') }}</label>

                            <div class="col-md-7">
                                <input id="merek_barang" type="text" class="form-control @error('merek') is-invalid @enderror" name="merek_barang" value="{{ $barang->merek }}" required autocomplete="merek_barang" placeholder="Merek" autofocus>

                                @error('merek')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="keterangan_barang" class="col-md-3 col-form-label text-md-right">{{ __('Keterangan') }}</label>

                            <div class="col-md-7">
                                <textarea name="keterangan_barang" id="keterangan_barang" cols="30" rows="3" required autocomplete="keterangan_barang" class="form-control @error('keterangan') is-invalid @enderror">{{ $barang->keterangan }}</textarea>

                                @error('keterangan')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="status" class="col-md-3 col-form-label text-md-right">{{ __('Status') }}</label>

                            <div class="col-md-7">
                                <select name="status" id="status" class="form-control @error('status') is-invalid @enderror">
                                        <option value="0" {{ $barang->status == 0 ? 'selected' : ''}}>Tidak Aktif</option>
                                        <option value="1" {{ $barang->status == 1 ? 'selected' : ''}}>Aktif</option>
                                </select>

                                @error('published')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        @role(['admin', 'admin'])


                        @endrole

                        <div class="form-group row mb-0">
                            <div class="col-md-7 offset-md-3">
                            @permission('barang-update')
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Edit') }}
                                </button>
                            @endpermission
                                <a href="{{ route('barang.index') }}" class="btn btn-danger text-white">{{ __('Cancel') }}</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/barang/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-end">
                <span class="flex-grow-1">Articles</span>
                @permission('barang-create')
                    <a href="{{ route('barang.create') }}" class="btn btn-sm btn-secondary">Create</a>
                @endpermission
                </div>

                <div class="card-body">

                    @if (session('message'))
                    <x-alert :type="session('type')" :message="session('message')" />
                    @endif

                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nama</th>
                                <th>Merek</th>
                                <th>status</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($barangs as $barang)
                            <tr>
                                <td>{{ $barang->id }}</td>
                                <td>{{ $barang->nama }}</td>
                                <td>{{ $barang->merek }}</td>
                                <td>{{ $barang->status == 1 ? 'Aktif' : 'Non-Aktif' }}</td>
                                <td>
                                    <form action="{{ route('barang.destroy', $barang->id) }}" method="post">
                                        @method('DELETE') @csrf
                                        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                            <a href="{{ route('barang.edit', $barang->id) }}" class="btn btn-info text-white">View</a>
                                        @permission('barang-delete')
                                            <button type="submit" class="btn btn-danger text-white">Delete</button>
                                        @endpermission
                                        </div>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                    {{ $barangs->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection